apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsdbredis
  labels:
    team: devalbedo
    version: 1.0.0
    environment: production
  annotations:
    description: ReplicaSet pod production database redis vs 1.0.0
    user: all service albedo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbredis
    matchExpressions:
      - key: app
        operator: In
        values:
          - dbredis
          - db
      - key: env
        operator: In
        values:
          - production
          - development
  template:
    metadata:
      name: poddbredis
      labels:
        app: dbredis
        env: production
      annotations:
        description: pod dbredis
    spec:
      containers:
        - name: dbredis
          image: redis:6.0
          hostname: dbredis
          command: 
            - redis-server /usr/local/etc/redis/redis.conf
          ports:
            - containerPort: 6300
          volumes:
            - ./config/redis.conf:/usr/local/etc/redis/redis.conf
          networks:
            default:
              external:
                name: netapp
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          
